languageCode = "en"
languageName = "English"
weight = 1
title = "Gospel Slides"

[params]
  displayName = "Gospel Slides"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/gospelslides_logo.jpg"
  description = "A powerful, lightweight theme for Hugo."

# [params.author]
#   name = ""
#   email = ""
#   image = "img/blowfish_logo.png"
#   headline = "A powerful, lightweight theme for Hugo."
#   bio = "A powerful, lightweight theme for Hugo."
#   links = [
#     { x-twitter = "" },
#     { github = "" },
#   ]